// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id, name, site, device_type)
VALUES ($1, $2, $3, $4)
RETURNING id, name, site, device_type, status, created_at, last_seen_at
`

type CreateDeviceParams struct {
	ID         pgtype.UUID
	Name       string
	Site       string
	DeviceType string
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ID,
		arg.Name,
		arg.Site,
		arg.DeviceType,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Site,
		&i.DeviceType,
		&i.Status,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, name, site, device_type, status, created_at, last_seen_at FROM devices WHERE id = $1
`

func (q *Queries) GetDevice(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Site,
		&i.DeviceType,
		&i.Status,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, name, site, device_type, status, created_at, last_seen_at FROM devices
WHERE ($1::text IS NULL OR site = $1)
  AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListDevicesParams struct {
	Column1 string
	Column2 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Site,
			&i.DeviceType,
			&i.Status,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleDevices = `-- name: ListStaleDevices :many
SELECT id, name, site, device_type, status, created_at, last_seen_at FROM devices
WHERE last_seen_at IS NULL OR last_seen_at < $1
`

func (q *Queries) ListStaleDevices(ctx context.Context, lastSeenAt pgtype.Timestamptz) ([]Device, error) {
	rows, err := q.db.Query(ctx, listStaleDevices, lastSeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Site,
			&i.DeviceType,
			&i.Status,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeviceStatus = `-- name: SetDeviceStatus :exec
UPDATE devices SET status = $2 WHERE id = $1
`

type SetDeviceStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) SetDeviceStatus(ctx context.Context, arg SetDeviceStatusParams) error {
	_, err := q.db.Exec(ctx, setDeviceStatus, arg.ID, arg.Status)
	return err
}

const updateDeviceLastSeen = `-- name: UpdateDeviceLastSeen :exec
UPDATE devices SET last_seen_at = $2 WHERE id = $1
`

type UpdateDeviceLastSeenParams struct {
	ID         pgtype.UUID
	LastSeenAt pgtype.Timestamptz
}

func (q *Queries) UpdateDeviceLastSeen(ctx context.Context, arg UpdateDeviceLastSeenParams) error {
	_, err := q.db.Exec(ctx, updateDeviceLastSeen, arg.ID, arg.LastSeenAt)
	return err
}
