// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID             int64
	DeviceID       pgtype.UUID
	AlertType      string
	Severity       string
	Message        string
	TriggeredAt    pgtype.Timestamptz
	AcknowledgedAt pgtype.Timestamptz
	ResolvedAt     pgtype.Timestamptz
	Active         bool
	Fingerprint    string
	Context        []byte
}

type Device struct {
	ID         pgtype.UUID
	Name       string
	Site       string
	DeviceType string
	Status     string
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
}

type Reading struct {
	ID           int64
	DeviceID     pgtype.UUID
	Ts           pgtype.Timestamptz
	TemperatureC pgtype.Float8
	PressureKpa  pgtype.Float8
	Rpm          pgtype.Float8
	Vibration    pgtype.Float8
	Payload      []byte
}
